#!/usr/bin/env sh

# Description: Plays selected items (or current directory) using VLC
# Shell: POSIX compliant
# Authors: acc15

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

get_selection() {
    if [ -s "$selection" ]; then
        cat "$selection"
    else
        printf "%s" "$2"
    fi
}

launch_vlc() {
    # macosx requires special handling here to make VLC open in foreground:
    # https://www.jviotti.com/2022/11/28/launching-macos-applications-from-the-command-line.htmlv
    if [ "$(uname)" = "Darwin" ]; then
        xargs -0 open -a vlc --args
    else
        xargs -0 nohup vlc >/dev/null 2>&1 &
    fi
}

clear_selection() {
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
}

{ get_selection | launch_vlc; } && clear_selection

